version: "3.7"
services:
  app:
    build:
      args:
        user: sammy
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: udemx-laravel
    container_name: udemx-laravel-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - udemx-laravel

  db:
    image: mysql:8.0
    container_name: udemx-laravel-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: udemx
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: tNbxUECKq
      MYSQL_USER: udemx_user
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - /var/lib/docker/volumes/udemx-laravel-mysql-server-volume/_data:/var/lib/mysql
    networks:
      - udemx-laravel

  nginx:
    image: nginx:alpine
    container_name: udemx-laravel-nginx
    restart: unless-stopped
    ports:
      - 8090:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - udemx-laravel

networks:
  udemx-laravel:
    driver: bridge
